### PR TITLE
Updated nonworking URLs

### PR DESCRIPTION
**Pull request by mars0i**
I can't test these changes because the relative paths are for janestreet, but I think they will work.

### CODE REVIEW

**Comment by ghost** [comment]
They don't seem to work on github though. I tried by clicking on `View` in the `Files changed` tab

**Comment by mars0i** [comment]
The URLs contain relative paths that point outside of the ppx_bin_prot repo, into the bin_prot repo.  That actually works in the second link in the current README.md in the original ppx_bin_prot repo.  If you click on the second link in the current README.md, it's true that it doesn't find the file, because the file got moved in bin_prot, but you can see in the URL bar that github is handling the relative paths correctly.

It didn't occur to me to try View in the PR.  I thought I could make it work just now by forking bin_prot--I hadn't seen any reason to do that previously.  However that doesn't make the links work in the View perspective, either.  The URL for the View version of the file is a little bit complicated, so that even with mars0i/bin_prot existing, the relative paths point somewhere nonexistent.  I could make them work in the PR, but then I don't think they'd work once the PR was accepted.  

So I don't think there's any way to test the links from inside the PR.  The relative paths are only going to work from within the normal janestreet location of ppx_bin_prot.   I don't see any reason why it won't, as I just made slight modifications to what was already there.  (Not a completely reliable criterion, but this isn't a Mars lander or a stock option transaction processor.) 

Or you could just try editing the README.md by hand with the same changes and see what happens.  The changes are trivial.  

(I thought the PR would make it easier, but maybe it's just making it harder!)

**Comment by ghost** [comment]
I see. Although I think we should use absolute URLs, at least it's clear what is being referenced. For instance one might want to read the readme from a local clone.

**Comment by mars0i** [comment]
If you prefer absolute URLs that's fine with me.  I used relative paths because only that's what was there previously.  Try this version.

**Comment by ghost** [comment]
Thanks. I imported the change in our internal review system

**Pull request closed without merging**
